# Generated by Django 5.2.7 on 2025-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM', models.CharField(blank=True, max_length=255, null=True)),
                ('PRENOM', models.CharField(blank=True, max_length=255, null=True)),
                ('NUM_TEL', models.FloatField(blank=True, null=True)),
                ('DATE_N', models.DateTimeField(blank=True, null=True)),
                ('RESIDENC', models.CharField(blank=True, max_length=255, null=True)),
                ('SEX', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=255, null=True)),
                ('GROUPAGE', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255, null=True)),
                ('DATE_DERNIER_DON', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_donor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Family_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
