# Generated by Django 5.2.7 on 2025-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_date_blood_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='NUM_TEL',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
