# Generated by Django 5.2.7 on 2025-11-07 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_donor_num_tel_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التبرع')),
                ('blood_type', models.CharField(max_length=3, verbose_name='فصيلة الدم')),
                ('quantity', models.CharField(default='1 وحدة', max_length=50, verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.donor', verbose_name='المتبرع')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'سجل التبرع',
                'verbose_name_plural': 'سجلات التبرعات',
                'db_table': 'donation_history',
            },
        ),
    ]
