# Generated by Django 5.2.7 on 2025-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_patient_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationhistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_blood_received',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_blood_received',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='received_blood_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='received_from_donor',
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
